<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <NoWarn>$(NoWarn);CS1591;CS0067;NU1510</NoWarn>
        <RootNamespace>Engine</RootNamespace>
        <AssemblyName>Engine</AssemblyName>
        <Configurations>Debug;Release;Direct3D11</Configurations>
        <PackageId>SurvivalcraftAPI.Engine</PackageId>
        <Title>SurvivalcraftAPI.Engine</Title><!--For NuGet Package-->
        <Version>1.8.2.3</Version><!--For NuGet Package-->
        <PackageProjectUrl>https://gitee.com/SC-SPM/SurvivalcraftApi</PackageProjectUrl>
        <RepositoryUrl>https://gitee.com/SC-SPM/SurvivalcraftApi</RepositoryUrl>
        <RepositoryType>Git</RepositoryType>
        <NeutralLanguage>zh-CN</NeutralLanguage>
        <LangVersion>preview</LangVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>disable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
        <Configuration Condition="'$(Configuration)' == ''">Debug</Configuration>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <TargetFrameworks>net10.0;net10.0-windows;net10.0-android</TargetFrameworks>
        <DefineConstants>DEBUG</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <TargetFrameworks>net10.0;net10.0-windows;net10.0-android</TargetFrameworks>
        <DebugType>none</DebugType>
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Direct3D11'">
        <TargetFramework>net10.0-windows</TargetFramework>
        <DebugType>none</DebugType>
        <DefineConstants>TRACE;RELEASE;DIRECT3D11</DefineConstants>
        <Optimize>true</Optimize>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'IOS'">
        <TargetFramework>net9.0-ios</TargetFramework>
        <DebugType>none</DebugType>
        <DefineConstants>TRACE;RELEASE;IOS</DefineConstants>
        <Optimize>true</Optimize>
        <IsTrimmable>true</IsTrimmable>
        <MtouchLink>None</MtouchLink>
        <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Angle'">
        <TargetFramework>net10.0-windows</TargetFramework>
        <DebugType>none</DebugType>
        <DefineConstants>TRACE;RELEASE;ANGLE</DefineConstants>
        <Optimize>true</Optimize>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Browser'">
        <TargetFramework>net10.0</TargetFramework>
        <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
        <DebugType>none</DebugType>
        <DefineConstants>TRACE;RELEASE;BROWSER</DefineConstants>
        <Optimize>true</Optimize>
        <IsAotCompatible>true</IsAotCompatible>
        <InvariantGlobalization>true</InvariantGlobalization>
        <InvariantTimezone>true</InvariantTimezone>
        <PublishTrimmed>true</PublishTrimmed>
        <TrimMode>full</TrimMode>
        <TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>
        <DebuggerSupport>false</DebuggerSupport>
        <WasmBuildNative>true</WasmBuildNative>
        <RunAOTCompilation>true</RunAOTCompilation>
        <WasmEnableThreads>true</WasmEnableThreads>
        <WasmEnableSIMD>true</WasmEnableSIMD>
        <WasmEnableExceptionHandling>false</WasmEnableExceptionHandling>
        <WasmStripILAfterAOT>true</WasmStripILAfterAOT>
    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
        <SupportedOSPlatformVersion>23.0</SupportedOSPlatformVersion>
    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-android' or '$(TargetFramework)' == 'net9.0-ios'">
        <DefineConstants>$(DefineConstants);MOBILE</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
        <EmbeddedResource Include="Resources\Lit.psh" Condition="'$(TargetFramework)' != 'net10.0-android'" />
        <EmbeddedResource Include="Resources\Lit.vsh" Condition="'$(TargetFramework)' != 'net10.0-android'" />
        <EmbeddedResource Include="Resources\Unlit.psh" Condition="'$(TargetFramework)' != 'net10.0-android'" />
        <EmbeddedResource Include="Resources\Unlit.vsh" Condition="'$(TargetFramework)' != 'net10.0-android'" />
        <EmbeddedResource Include="Resources\Debugfont.lst" Condition="'$(TargetFramework)' != 'net10.0-android'" />
        <EmbeddedResource Include="Resources\Debugfont.png" Condition="'$(TargetFramework)' != 'net10.0-android'" />
        <EmbeddedResource Include="Resources\icon.png" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="NVorbis" Version="0.10.5" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" /><!--An powerful and popular audio libaury-->
        <PackageReference Include="NLayer.NAudioSupport" Version="1.4.0" /><!--MP3 support-->
        <PackageReference Include="NAudio.Flac.Unknown.Mod" Version="1.0.4" PrivateAssets="all" Condition="'$(Configuration)' != 'IOS'" /><!--Source: https://github.com/XiaofengdiZhu/NAudio.Flac/ -->
        <PackageReference Include="NAudio.Core" Version="2.2.1" /><!--Resolve reference confliction between NLayer.NAudioSupport and NAudio.Flac.Unknown.Mod-->
        <PackageReference Include="Silk.NET.Windowing" Version="2.23.0" Condition="'$(Configuration)' != 'Browser'" />
        <PackageReference Include="Silk.NET.OpenGLES" Version="2.23.0" Condition="'$(Configuration)' != 'Direct3D11'" />
        <PackageReference Include="Silk.NET.OpenAL" Version="2.23.0" Condition="'$(Configuration)' != 'Browser'" />
        <PackageReference Include="Silk.NET.Input" Version="2.23.0" Condition="'$(TargetFramework)' != 'net10.0-android' and '$(Configuration)' != 'Browser'" />
        <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.3" /><!--To solve the warning of Silk.NET useing an old version of this-->
        <PackageReference Include="System.Net.Http" Version="4.3.4" />
        <PackageReference Include="System.Private.Uri" Version="4.3.2" />
        <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
        <PackageReference Include="Xamarin.AndroidX.Core" Version="1.17.0.1" Condition="'$(TargetFramework)' == 'net10.0-android'" />
        <PackageReference Include="NativeFileDialogCore" Version="1.0.3" Condition="'$(TargetFramework)' != 'net10.0-android' and '$(RuntimeIdentifier)' != 'browser-wasm'" />
    </ItemGroup>
    <ItemGroup Condition="'$(Configuration)' == 'Direct3D11'">
        <PackageReference Include="SharpDX" Version="4.2.0" />
        <PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
        <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
        <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
        <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
    </ItemGroup>
    <ItemGroup>
        <Compile Remove="Engine.Graphics\DXWrapper.cs" Condition="'$(Configuration)' != 'Direct3D11'" />
        <Compile Remove="Engine.Graphics\GLWrapper.cs" Condition="'$(Configuration)' == 'Direct3D11'" />
        <Compile Remove="Engine.Graphics\EGL.cs" Condition="'$(Configuration)' != 'Angle' and '$(Configuration)' != 'Browser'" />
        <Compile Remove="Engine.Browser\**\*.cs" Condition="'$(Configuration)' != 'Browser'" />
        <Compile Remove="Engine.Serialization\*Archive.cs" Condition="'$(Configuration)' == 'Browser'" />
        <Compile Remove="Engine.Serialization\*Serializer.cs" Condition="'$(Configuration)' == 'Browser'" />
        <Compile Remove="Engine.Serialization\ISerializable.cs" Condition="'$(Configuration)' == 'Browser'" />
    </ItemGroup>
    <ItemGroup Condition="'$(Configuration)' == 'IOS'">
        <Reference Include="Bass.Net" HintPath="Bass.Net.dll" />
    </ItemGroup>
    </Project>
