<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="Engine.props" />
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="NativeFileDialogCore" Version="1.0.3" />
    </ItemGroup>
    <ItemGroup>
        <Compile Remove="Engine.Graphics\EGL.cs" Condition="'$(Configuration)' != 'Angle'" />
    </ItemGroup>
</Project>
