<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <NoWarn>$(NoWarn);CS1591;CS0067</NoWarn>
        <RootNamespace>Engine</RootNamespace>
        <AssemblyName Condition="'$(Configuration)' != 'Direct3D11'">Engine</AssemblyName>
        <AssemblyName Condition="'$(Configuration)' == 'Direct3D11'">EngineDirect3D11</AssemblyName>
        <Configurations>Debug;Release;Direct3D11</Configurations>
        <PackageId>SurvivalcraftAPI.Engine</PackageId>
        <Title>SurvivalcraftAPI.Engine</Title><!--For NuGet Package-->
        <Version>1.8.1.3</Version><!--For NuGet Package-->
        <PackageProjectUrl>https://gitee.com/SC-SPM/SurvivalcraftApi</PackageProjectUrl>
        <RepositoryUrl>https://gitee.com/SC-SPM/SurvivalcraftApi</RepositoryUrl>
        <RepositoryType>Git</RepositoryType>
        <NeutralLanguage>zh-CN</NeutralLanguage>
        <LangVersion>preview</LangVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>disable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <TargetFrameworks>net9.0;net9.0-windows;net9.0-android</TargetFrameworks>
        <DefineConstants>DEBUG</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <TargetFrameworks>net9.0;net9.0-windows;net9.0-android</TargetFrameworks>
        <DebugType>none</DebugType>
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Direct3D11'">
        <TargetFramework>net9.0-windows</TargetFramework>
        <DebugType>none</DebugType>
        <DefineConstants>TRACE;RELEASE;DIRECT3D11</DefineConstants>
        <Optimize>true</Optimize>
    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'net9.0-android'">
        <SupportedOSPlatformVersion>23.0</SupportedOSPlatformVersion>
    </PropertyGroup>
    <ItemGroup>
        <EmbeddedResource Include="Resources\Lit.psh" Condition="'$(TargetFramework)' != 'net9.0-android'" />
        <EmbeddedResource Include="Resources\Lit.vsh" Condition="'$(TargetFramework)' != 'net9.0-android'" />
        <EmbeddedResource Include="Resources\Unlit.psh" Condition="'$(TargetFramework)' != 'net9.0-android'" />
        <EmbeddedResource Include="Resources\Unlit.vsh" Condition="'$(TargetFramework)' != 'net9.0-android'" />
        <EmbeddedResource Include="Resources\Debugfont.lst" Condition="'$(TargetFramework)' != 'net9.0-android'" />
        <EmbeddedResource Include="Resources\Debugfont.png" Condition="'$(TargetFramework)' != 'net9.0-android'" />
        <EmbeddedResource Include="Resources\icon.png" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="NVorbis" Version="0.10.5" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" /><!--An powerful and popular audio libaury-->
        <PackageReference Include="NLayer.NAudioSupport" Version="1.4.0" /><!--MP3 support-->
        <PackageReference Include="NAudio.Flac.Unknown.Mod" Version="1.0.3" PrivateAssets="all" /><!--Source: https://github.com/XiaofengdiZhu/NAudio.Flac/ -->
        <PackageReference Include="NAudio.Core" Version="2.2.1" /><!--Resolve reference confliction between NLayer.NAudioSupport and NAudio.Flac.Unknown.Mod-->
        <PackageReference Include="Silk.NET.Windowing" Version="2.22.0" />
        <PackageReference Include="Silk.NET.OpenGLES" Version="2.22.0" Condition="'$(Configuration)' != 'Direct3D11'" />
        <PackageReference Include="Silk.NET.OpenAL" Version="2.22.0" />
        <PackageReference Include="Silk.NET.Input" Version="2.22.0" Condition="'$(TargetFramework)' != 'net9.0-android'" />
        <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="9.0.3" /><!--To solve the warning of Silk.NET useing an old version of this-->
        <PackageReference Include="System.Net.Http" Version="4.3.4" />
        <PackageReference Include="System.Private.Uri" Version="4.3.2" />
        <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
        <PackageReference Include="Tomlyn" Version="0.19.0" />
    </ItemGroup>
    <ItemGroup Condition="'$(Configuration)' == 'Direct3D11'">
        <PackageReference Include="SharpDX" Version="4.2.0" />
        <PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
        <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
        <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
        <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
    </ItemGroup>
    <ItemGroup>
        <Compile Remove="Engine.Graphics\DXWrapper.cs" Condition="'$(Configuration)' != 'Direct3D11'" />
        <Compile Remove="Engine.Graphics\GLWrapper.cs" Condition="'$(Configuration)' == 'Direct3D11'" />
    </ItemGroup>
    <ItemGroup>
      <EditorConfigFiles Remove=".editorconfig" />
    </ItemGroup>
</Project>
