<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Engine</AssemblyName>
        <RootNamespace>Engine</RootNamespace>
        <TargetFramework>net9.0-ios</TargetFramework>
        <NeutralLanguage>zh-CN</NeutralLanguage>
        <LangVersion>preview</LangVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <Nullable>disable</Nullable>
        <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
        <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
        <IsTrimmable>true</IsTrimmable>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <MtouchLink>None</MtouchLink>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DebugType>none</DebugType>
        <MtouchLink>None</MtouchLink>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="..\Engine\**\*.cs" />
    </ItemGroup>
    <ItemGroup>
        <Compile Remove="..\Engine\obj\**\*.cs" />
        <Compile Remove="..\Engine\Engine.Graphics\DXWrapper.cs" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Resources\Debugfont.lst" />
        <EmbeddedResource Include="Resources\Debugfont.png" />
        <EmbeddedResource Include="Resources\icon.png" />
        <EmbeddedResource Include="Resources\Lit.psh" />
        <EmbeddedResource Include="Resources\Lit.vsh" />
        <EmbeddedResource Include="Resources\Unlit.psh" />
        <EmbeddedResource Include="Resources\Unlit.vsh" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="NVorbis" Version="0.10.5" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
        <PackageReference Include="NLayer.NAudioSupport" Version="1.4.0" />
        <PackageReference Include="NAudio.Core" Version="2.2.1" />
        <PackageReference Include="Silk.NET.Windowing" Version="2.22.0" />
        <PackageReference Include="Silk.NET.OpenGLES" Version="2.22.0" />
        <PackageReference Include="Silk.NET.OpenAL" Version="2.22.0" />
        <PackageReference Include="Silk.NET.Input" Version="2.22.0" />
        <PackageReference Include="System.Net.Http" Version="4.3.4" />
        <PackageReference Include="System.Private.Uri" Version="4.3.2" />
        <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
        <PackageReference Include="Tomlyn" Version="0.19.0" />
    </ItemGroup>
    <ItemGroup>
        <Reference Include="Bass.Net">
            <HintPath>Bass.Net.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>
