<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-ios17.5</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>
      <ApplicationId>com.survivalcraft.api</ApplicationId>
    <!--
      Enable full trimming in Release mode.
      To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/trimming-options#trimming-granularity
    -->
    <TrimMode Condition="'$(Configuration)' == 'Release'">full</TrimMode>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <AssemblyName>Survivalcraft</AssemblyName>
    <PublishAot>False</PublishAot>
    <ProvisioningType>manual</ProvisioningType>
    <CodesignKey>iPhone Developer</CodesignKey>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
      <EnableNETAnalyzers>false</EnableNETAnalyzers>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <MtouchLink>Full</MtouchLink>
    <MtouchNoSymbolStrip>True</MtouchNoSymbolStrip>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <BuildIpa>True</BuildIpa>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <MtouchLink>Full</MtouchLink>
    <MtouchNoSymbolStrip>True</MtouchNoSymbolStrip>
    <EnableSGenConc>True</EnableSGenConc>
  </PropertyGroup>
    <ItemGroup>
        <Compile Include="..\Survivalcraft.Windows\**\*.cs" Exclude="..\Survivalcraft.Windows\obj\**\*.cs" />
    </ItemGroup>
    <ItemGroup>
      <Compile Remove="..\Survivalcraft.Windows\Properties\AssemblyInfo.cs" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Jint" Version="4.4.1" />
      <PackageReference Include="NAudio.Flac.Unknown.Mod" Version="1.0.3" />
      <PackageReference Include="Silk.NET.OpenGLES" Version="2.22.0" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="..\Survivalcraft.Windows\Content.zip" Link="Content.zip">
            <LogicalName>Game.Content.zip</LogicalName>
        </EmbeddedResource>
        <None Include="..\Survivalcraft.Windows\init.js" Link="init.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Engine\Engine.csproj" />
      <ProjectReference Include="..\EntitySystem\EntitySystem.csproj" />
    </ItemGroup>
</Project>
