<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Survivalcraft</AssemblyName>
        <RootNamespace>Game</RootNamespace>
        <TargetFramework>net9.0-ios</TargetFramework>
        <LangVersion>preview</LangVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>disable</Nullable>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>true</ImplicitUsings>
        <ProvisioningType>manual</ProvisioningType>
        <EnableSGenConc>true</EnableSGenConc>
        <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
        <IsTrimmable>true</IsTrimmable>
        <ApplicationId>com.survivalcraft.api</ApplicationId>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <MtouchLink>None</MtouchLink>
        <EnableHotReload>false</EnableHotReload>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DebugType>none</DebugType>
        <MtouchLink>None</MtouchLink>
        <MtouchUseLlvm>false</MtouchUseLlvm>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="..\Survivalcraft.Windows\**\*.cs" Exclude="..\Survivalcraft.Windows\obj\**\*.cs" />
    </ItemGroup>
    <ItemGroup>
        <Compile Remove="..\Survivalcraft.Windows\Properties\AssemblyInfo.cs" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="..\Survivalcraft.Windows\Content.zip" Link="Content.zip">
            <LogicalName>Game.Content.zip</LogicalName>
        </EmbeddedResource>
        <None Include="..\Survivalcraft.Windows\init.js" Link="init.js">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Engine.IOS\Engine.IOS.csproj" />
        <ProjectReference Include="..\EntitySystem.IOS\EntitySystem.IOS.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Reference Include="Bass.Net">
            <HintPath>..\Engine.IOS\Bass.Net.dll</HintPath>
        </Reference>
    </ItemGroup>
    <ItemGroup>
        <!--IOS真机原生库加载-->
        <NativeReference Include="native/bass.xcframework/ios-arm64_armv7_armv7s/bass.framework" Condition="'$(RuntimeIdentifier)'=='ios-arm64'">
            <Kind>Framework</Kind>
            <ForceLoad>true</ForceLoad>
        </NativeReference>
        <NativeReference Include="native/bassflac.xcframework/ios-arm64_armv7_armv7s/bassflac.framework" Condition="'$(RuntimeIdentifier)'=='ios-arm64'">
            <Kind>Framework</Kind>
            <ForceLoad>true</ForceLoad>
        </NativeReference>
        <!--IOS模拟器原生库加载-->
        <NativeReference Include="native/bass.xcframework/ios-arm64_i386_x86_64-simulator/bass.framework" Condition="'$(RuntimeIdentifier)'=='iossimulator-arm64'">
            <Kind>Framework</Kind>
            <ForceLoad>true</ForceLoad>
        </NativeReference>
        <NativeReference Include="native/bassflac.xcframework/ios-arm64_i386_x86_64-simulator/bassflac.framework" Condition="'$(RuntimeIdentifier)'=='iossimulator-arm64'">
            <Kind>Framework</Kind>
            <ForceLoad>true</ForceLoad>
        </NativeReference>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="NuGet.Versioning" Version="6.14.0" />
    </ItemGroup>
</Project>
