<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
        <RootNamespace>Game</RootNamespace>
        <AssemblyName>Survivalcraft</AssemblyName>
        <TargetFramework>net10.0</TargetFramework>
        <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
        <ApplicationVersion>2.4.0.0</ApplicationVersion>
        <AssemblyVersion>2.4.0.0</AssemblyVersion>
        <FileVersion>2.4.0.0</FileVersion>
        <LangVersion>preview</LangVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>disable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <OutputType>Exe</OutputType>
        <IsAotCompatible>true</IsAotCompatible>
        <InvariantGlobalization>true</InvariantGlobalization>
        <EmccFlags>-s FULL_ES3=1 -lopenal -lGL -s</EmccFlags>
        <WasmMainJSPath>main.js</WasmMainJSPath>
    </PropertyGroup>
    <PropertyGroup>
        <PublishTrimmed>true</PublishTrimmed>
        <WasmBuildNative>true</WasmBuildNative>
        <RunAOTCompilation>true</RunAOTCompilation>
        <!-- Disable SIMD support as it's prerelease only on Safari -->
        <WasmEnableSIMD>false</WasmEnableSIMD>
        <!-- Normal,JustInterp,Full,FullInterp,Hybrid,LLVMOnly,LLVMOnlyInterp -->
        <!-- <AOTMode>LLVMOnly</AOTMode> -->
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Browser' ">
        <DefineConstants>DEBUG;BROWSER</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Engine\Engine.csproj" SetTargetFramework="TargetFramework=net10.0" />
        <ProjectReference Include="..\EntitySystem\EntitySystem.csproj" SetTargetFramework="TargetFramework=net10.0" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="NuGet.Versioning" Version="7.0.1" />
    </ItemGroup>
    <ItemGroup>
        <NativeFileReference Include="Native/libEGL.c" ScanForPInvokes="true" />
        <NativeFileReference Include="Native/openal32.c" ScanForPInvokes="true" />
        <NativeFileReference Include="Native/emscripten.c" ScanForPInvokes="true" />
        <WasmExtraFilesToDeploy Include="index.html" />
        <WasmExtraFilesToDeploy Include="main.js" />
        <WasmExtraFilesToDeploy Include="$(MSBuildThisFileDirectory)Assets\**" TargetPath="Assets/%(RecursiveDir)%(Filename)%(Extension)" />
    </ItemGroup>
    <ItemGroup>
        <Compile Include="..\Survivalcraft.Windows\**\*.cs" Exclude="..\Survivalcraft.Windows\obj\**\*.cs"/>
    </ItemGroup>
</Project>
