<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <NoWarn>$(NoWarn);CS1591;XA0141;XA4301</NoWarn>
        <RootNamespace>Game</RootNamespace>
        <AssemblyName>Survivalcraft</AssemblyName>
        <Product>Survivalcraft</Product>
        <TargetFramework>net10.0-android</TargetFramework>
        <RuntimeIdentifier>android-arm64</RuntimeIdentifier>
        <ApplicationVersion>2.4.0.0</ApplicationVersion>
        <AssemblyVersion>2.4.0.0</AssemblyVersion>
        <FileVersion>2.4.0.0</FileVersion>
        <LangVersion>preview</LangVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>disable</Nullable>
        <AndroidUseLatestPlatformSdk>true</AndroidUseLatestPlatformSdk>
        <AndroidApplication>true</AndroidApplication>
        <ApplicationId>com.candy.SurvivalcraftAPI1_8</ApplicationId>
        <AndroidStoreUncompressedFileExtensions>.dll</AndroidStoreUncompressedFileExtensions>
        <AndroidPackageFormat>apk</AndroidPackageFormat>
        <AndroidUseDesignerAssembly>true</AndroidUseDesignerAssembly>
        <!--签名-->
        <AndroidKeyStore>true</AndroidKeyStore>
        <AndroidSigningKeyAlias>androiddebugkey</AndroidSigningKeyAlias>
        <AndroidSigningKeyStore>Signing.keystore</AndroidSigningKeyStore>
        <AndroidSigningStorePass>android</AndroidSigningStorePass>
        <AndroidSigningKeyPass>android</AndroidSigningKeyPass>
        <!--优化-->
        <PublishTrimmed>false</PublishTrimmed><!--切记不要修改，如果修改会导致运行时不完整-->
        <TrimMode>partial</TrimMode>
        <AndroidDexTool>d8</AndroidDexTool>
        <AndroidEnableSGenConcurrent>false</AndroidEnableSGenConcurrent>
        <AndroidLinkMode>None</AndroidLinkMode>
        <AndroidLintEnabled>false</AndroidLintEnabled>
        <AndroidStripILAfterAOT>true</AndroidStripILAfterAOT>
        <AndroidUseInterpreter>false</AndroidUseInterpreter>
        <EnableLLVM>true</EnableLLVM>
        <RunAOTCompilation>false</RunAOTCompilation>
        <Configuration Condition="'$(Configuration)' == ''">Debug</Configuration>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DefineConstants>DEBUG</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DebugType>none</DebugType>
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
        <AndroidAsset Include="..\Engine\Resources\Lit.psh" Link="Assets\Lit.psh">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AndroidAsset>
        <AndroidAsset Include="..\Engine\Resources\Lit.vsh" Link="Assets\Lit.vsh">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AndroidAsset>
        <AndroidAsset Include="..\Engine\Resources\UnLit.psh" Link="Assets\Unlit.psh">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AndroidAsset>
        <AndroidAsset Include="..\Engine\Resources\UnLit.vsh" Link="Assets\Unlit.vsh">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AndroidAsset>
        <AndroidAsset Include="..\Engine\Resources\Debugfont.png" Link="Assets\Debugfont.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AndroidAsset>
        <AndroidAsset Include="..\Engine\Resources\Debugfont.lst" Link="Assets\Debugfont.lst">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AndroidAsset>
        <AndroidAsset Include="..\Survivalcraft.Windows\Content.zip">
            <Link>Assets\Content.zip</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AndroidAsset>
        <AndroidAsset Include="..\Survivalcraft.Windows\init.js">
            <Link>Assets\init.js</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AndroidAsset>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Jint" Version="4.4.2"/>
        <PackageReference Include="NAudio.Flac.Unknown.Mod" Version="1.0.4"/>
        <PackageReference Include="NuGet.Versioning" Version="7.0.1" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\EntitySystem\EntitySystem.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <Compile Include="..\Survivalcraft.Windows\**\*.cs" Exclude="..\Survivalcraft.Windows\obj\**\*.cs"/>
    </ItemGroup>
</Project>