<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
        <RootNamespace>EntitySystem</RootNamespace>
        <AssemblyName>EntitySystem</AssemblyName>
        <Configurations>Debug;Release;Direct3D11</Configurations>
        <PackageId>SurvivalcraftAPI.EntitySystem</PackageId>
        <Title>SurvivalcraftAPI.EntitySystem</Title><!--For NuGet Package-->
        <Version>1.8.2.3</Version><!--For NuGet Package-->
        <PackageProjectUrl>https://gitee.com/SC-SPM/SurvivalcraftApi</PackageProjectUrl>
        <RepositoryUrl>https://gitee.com/SC-SPM/SurvivalcraftApi</RepositoryUrl>
        <RepositoryType>Git</RepositoryType>
        <NeutralLanguage>zh-CN</NeutralLanguage>
        <LangVersion>preview</LangVersion>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
        <Configuration Condition="'$(Configuration)' == ''">Debug</Configuration>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <TargetFrameworks>net10.0;net10.0-windows;net10.0-android</TargetFrameworks>
        <DefineConstants>DEBUG</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <TargetFrameworks>net10.0;net10.0-windows;net10.0-android</TargetFrameworks>
        <DebugType>none</DebugType>
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Direct3D11'">
        <TargetFramework>net10.0-windows</TargetFramework>
        <DebugType>none</DebugType>
        <DefineConstants>TRACE;RELEASE;DIRECT3D11</DefineConstants>
        <Optimize>true</Optimize>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'IOS'">
        <TargetFramework>net9.0-ios</TargetFramework>
        <DebugType>none</DebugType>
        <DefineConstants>TRACE;RELEASE;IOS;MOBILE</DefineConstants>
        <Optimize>true</Optimize>
        <IsTrimmable>true</IsTrimmable>
        <MtouchLink>None</MtouchLink>
        <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Angle'">
        <TargetFramework>net10.0-windows</TargetFramework>
        <DebugType>none</DebugType>
        <DefineConstants>TRACE;RELEASE;ANGLE</DefineConstants>
        <Optimize>true</Optimize>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Browser'">
        <TargetFramework>net10.0</TargetFramework>
        <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
        <DefineConstants>DEBUG;BROWSER</DefineConstants>
        <IsAotCompatible>true</IsAotCompatible>
        <InvariantGlobalization>false</InvariantGlobalization>
        <PublishTrimmed>true</PublishTrimmed>
        <WasmBuildNative>true</WasmBuildNative>
        <RunAOTCompilation>true</RunAOTCompilation>
        <WasmEnableSIMD>false</WasmEnableSIMD>
    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-android' or '$(TargetFramework)' == 'net9.0-ios'">
        <DefineConstants>$(DefineConstants);MOBILE</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Engine\Engine.csproj" />
    </ItemGroup>
</Project>